### ISSUE TITLE
Not working with latest sequelize

### ISSUE THREAD

**Issue by kytwb** [evantahler/ah-sequelize-plugin#21]
I've updated sequelize locally, but looks like things aren't working anymore.

```
api_1 | 2015-05-30 21:56:16 - debug:  > start: sequelize /app/node_modules/ah-sequelize-plugin/initializers/sequelize.js
api_1 | Executing (default): SELECT NOW()
api_1 | 2015-05-30 21:56:17 - warning:  TypeError: undefined is not a function
api_1 |     at Object.api.sequelize.migrate (/app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:18:48)
api_1 |     at Object.api.sequelize.autoMigrate (/app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:62:27)
api_1 |     at /app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:96:21
api_1 |     at /app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:77:11
api_1 |     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:24:31)
api_1 |     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:454:31)
api_1 |     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:530:18)
api_1 |     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:646:14)
api_1 |     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:177:16)
api_1 |     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:187:10)
api_1 |     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
api_1 |     at processImmediate [as _immediateCallback] (timers.js:358:17)
api_1 | { [TypeError: undefined is not a function] level: 'warning', timestamp: '2015-05-30T21:56:17.280Z' }
api_1 | 2015-05-30 21:56:17 - debug:    started: sequelize /app/node_modules/ah-sequelize-plugin/initializers/sequelize.js
api_1 | 2015-05-30 21:56:17 - emerg: Error with initilizer step: start
api_1 | 2015-05-30 21:56:17 - emerg: TypeError: undefined is not a function
api_1 |     at Object.api.sequelize.migrate (/app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:18:48)
api_1 |     at Object.api.sequelize.autoMigrate (/app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:62:27)
api_1 |     at /app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:96:21
api_1 |     at /app/node_modules/ah-sequelize-plugin/initializers/sequelize.js:77:11
api_1 |     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:24:31)
api_1 |     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:454:31)
api_1 |     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:530:18)
api_1 |     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:646:14)
api_1 |     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:177:16)
api_1 |     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:187:10)
api_1 |     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
api_1 |     at processImmediate [as _immediateCallback] (timers.js:358:17)
```

With relevant `package.json` excerpt:

```
kytwb@continuous:~/Documents/Continuous/React/CRM/api$ cat package.json | grep sequelize
    "ah-sequelize-plugin": "^0.6.0",
    "sequelize": "^3.1.1",
    "sequelize-cli": "^1.7.0"
```

**Comment by kytwb** [comment]
Related to #19.
